version: "3.2"  # optional since v1.27.0
services:
  crude:
    build: .
    command: npm start
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
  db:
    container_name: 'bd-crude'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    ports: 
      - '3311:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db_crude_mysql
      - TZ=America/Sao_Paulo
  